security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://${app.auth-service}:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /accounts
  port: 6000

---
spring:
  config:
    activate:
      on-profile: docker-compose

spring.data.mongodb.host: account-mongodb

---
spring:
  config:
    activate:
      on-profile: prod