server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
---
spring.profiles: docker-compose

spring.data.mongodb.host: auth-mongodb
---
spring.profiles: prod